version: "3.9"

services:
  api:
    container_name: Version_API
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KEY: ${KEY}
      CERT: ${CERT}
    ports:
      - "443:8443/tcp"
      - "80:8080/tcp"
