name: Deploy API
on:
  push:
    branches:
      - main
    paths:
      - "src/api/**/*"
      - ".github/**/*"
      - "src/model/**/*"
      - "src/connect.ts"
      - "package*.json"
      - "Dockerfile"
      - "docker-compose.y*ml"

jobs:
  test:
    runs-on: "ubuntu-latest"
    name: Test API
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "current"

      - name: Install dependencies
        run: |
          npm ci
          sudo npm install -g autocannon ts-node typescript

      - name: Start API and test
        run: |
          ts-node src/api/index.ts &
          sleep 15s
          autocannon localhost:8080/bedrock/latest
          autocannon localhost:8080/

  deploy:
    runs-on: ARM64
    name: Deploy container
    environment:
      name: "deploy_container"
      url: https://mcpeversions.sirherobrine23.org/
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker-compose build

      - name: Down container
        run: docker-compose down

      - name: Up container
        run: docker-compose up -d
        env:
          KEY: "${{ secrets.CA_KEY }}"
          CERT: "${{ secrets.CA_CERT }}"

      - name: Docker Clean
        run: docker system prune -f
