name: Deploy API
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ARM64
    name: Deploy container
    environment:
      name: "deploy_container"
      url: https://mcpeversions.sirherobrine23.org/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker-compose build

      - name: Down container
        run: docker-compose down

      - name: Up container
        run: docker-compose up -d
        env:
          KEY: "${{ secrets.CA_KEY }}"
          CERT: "${{ secrets.CA_CERT }}"

      - name: Docker Clean
        run: docker system prune -f
