name: Deploy
on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ARM64
    name: Deploy container
    environment:
      name: 'API
      url: https://version.api.bdsmaneger.com/
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Build Docker image
        run: docker-compose build

      - name: Down container
        run: docker-compose down

      - name: Up container
        run: docker-compose up -d
        env:
          KEY: "${{ secrets.CA_KEY }}"
          CERT: "${{ secrets.CA_CERT }}"

      - name: Test
        run: |
          sleep 30
          docker-compose logs
          curl -v https://localhost:80/

      - name: Docker Clean
        run: docker system prune -f