name: Find new versions
on:
  schedule:
    - cron: 0 */2 * * *
  push:
    branches:
      - main
jobs:
  findVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node JS
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.x

      - name: Install Node Packages
        run: npm install -d --no-save

      - name: Install ts-node
        run: sudo npm install -g ts-node

      - name: Find and Update database
        run: ts-node src/fetchVersion/index.ts
        env:
          MONGO_USER: "${{ secrets.MONGO_USER }}"
          MONGO_PASSWORD: "${{ secrets.MONGO_PASSWORD }}"