name: Test Find versions
on:
  pull_request:
    branches: [main]

jobs:
  findVersion:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - bedrock
          - java
          - spigot
          - pocketmine
          - paper
          - powernukkit
    name: "server ${{ matrix.platform }}"
    steps:
      - name: Up mongo server
        run: |
          docker run --rm --name mongodb -d -p 27017:27017 mongo
          # BDSVERSIONDB="mongodb://localhost/bdsversion"
          echo "BDSVERSIONDB=mongodb://$(docker inspect  -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mongodb)/bdsversion" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        name: Checkout code

      - name: Setup Node JS
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          npm ci
          sudo npm install -g ts-node typescript

      - name: Find and Update database
        run: npm run search -- --${{ matrix.platform }}

      - name: Upload result
        run: |
          ts-node src/exports.ts
          cat versions.json > $GITHUB_STEP_SUMMARY