name: Find new versions
on:
  schedule:
    - cron: 0 */2 * * *
  push:
    branches:
      - main
jobs:
  findVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup git User
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Setup Node JS
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 16.x

      - name: Install Node Packages
        run: npm install -d --no-save

      - name: Check Versions
        run: npm run find_version

      - name: Create Commit Files
        continue-on-error: true
        if: env.COMMIT_CHANGES == 'true'
        run: git push
